import { mutation } from "./_generated/server";

// Sample Dubai venues data for MVP testing
export const seedPlaces = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("places").first();
    if (existing) {
      return { message: "Database already seeded" };
    }

    const places = [
      // Marina - Outdoor Cafes
      {
        name: "The Surf Cafe",
        nameAr: "مقهى ذا سيرف",
        coverImage: "/images/surf-cafe.jpg",
        gallery: ["/images/surf-cafe-1.jpg", "/images/surf-cafe-2.jpg"],
        latitude: 25.0801,
        longitude: 55.1384,
        area: "Marina",
        nearMetro: true,
        metroStation: "DMCC",
        metroWalkTime: 5,
        tags: ["outdoor", "family-friendly", "waterfront"],
        cuisine: ["International", "Breakfast"],
        priceLevel: "Mid",
        rating: 4.5,
        noise: "Moderate",
        openingHours: {
          monday: "7:00-22:00",
          tuesday: "7:00-22:00",
          wednesday: "7:00-22:00",
          thursday: "7:00-22:00",
          friday: "7:00-23:00",
          saturday: "7:00-23:00",
          sunday: "7:00-22:00",
        },
        phone: "+971-4-123-4567",
        bookingUrl: "https://example.com/book/surf-cafe",
        website: "https://surfcafe.ae",
        highlights: "Beachfront views with relaxed vibes, perfect for families and groups seeking outdoor dining with marina views.",
        parkingNote: "Valet parking available at marina",
        seatingTypes: ["outdoor", "sofa", "high-chair"],
        category: "cafe",
        verified: true,
        lastUpdated: Date.now(),
      },

      // Business Bay - Indoor Restaurants
      {
        name: "Zafran Indian Bistro",
        nameAr: "زعفران مطعم هندي",
        coverImage: "/images/zafran.jpg",
        gallery: ["/images/zafran-1.jpg", "/images/zafran-2.jpg"],
        latitude: 25.1862,
        longitude: 55.2666,
        area: "Business Bay",
        nearMetro: true,
        metroStation: "Business Bay",
        metroWalkTime: 3,
        tags: ["indoor", "family-friendly"],
        cuisine: ["Indian", "Asian"],
        priceLevel: "Mid",
        rating: 4.7,
        noise: "Quiet",
        openingHours: {
          monday: "12:00-15:00, 18:00-23:00",
          tuesday: "12:00-15:00, 18:00-23:00",
          wednesday: "12:00-15:00, 18:00-23:00",
          thursday: "12:00-15:00, 18:00-23:00",
          friday: "12:00-15:00, 18:00-23:30",
          saturday: "12:00-15:00, 18:00-23:30",
          sunday: "12:00-15:00, 18:00-23:00",
        },
        phone: "+971-4-234-5678",
        bookingUrl: "https://example.com/book/zafran",
        website: "https://zafran.ae",
        highlights: "Authentic Indian cuisine in an elegant setting, perfect for quiet family dinners with view of city skyline.",
        parkingNote: "Underground parking in building",
        seatingTypes: ["indoor", "booth", "high-chair"],
        category: "restaurant",
        verified: true,
        lastUpdated: Date.now(),
      },

      // Downtown - Waterfront Fine Dining
      {
        name: "Armani/Ristorante",
        nameAr: "أرماني ريستورانتي",
        coverImage: "/images/armani.jpg",
        gallery: ["/images/armani-1.jpg", "/images/armani-2.jpg"],
        latitude: 25.1972,
        longitude: 55.2744,
        area: "Downtown",
        nearMetro: true,
        metroStation: "Burj Khalifa/Dubai Mall",
        metroWalkTime: 8,
        tags: ["indoor", "waterfront"],
        cuisine: ["Italian", "Fine Dining"],
        priceLevel: "Lux",
        rating: 4.9,
        noise: "Quiet",
        openingHours: {
          monday: "19:00-23:00",
          tuesday: "19:00-23:00",
          wednesday: "19:00-23:00",
          thursday: "19:00-23:00",
          friday: "19:00-23:30",
          saturday: "19:00-23:30",
          sunday: "19:00-23:00",
        },
        phone: "+971-4-888-3666",
        bookingUrl: "https://example.com/book/armani",
        website: "https://armanihotels.com",
        highlights: "World-class Italian dining with stunning Burj Khalifa fountain views, perfect for special occasions.",
        parkingNote: "Valet parking at Burj Khalifa",
        seatingTypes: ["indoor", "premium"],
        category: "restaurant",
        verified: true,
        lastUpdated: Date.now(),
      },

      // JBR - Family Beach Cafe
      {
        name: "The Beach House",
        nameAr: "بيت الشاطئ",
        coverImage: "/images/beach-house.jpg",
        gallery: ["/images/beach-house-1.jpg"],
        latitude: 25.0782,
        longitude: 55.1322,
        area: "JBR",
        nearMetro: true,
        metroStation: "DMCC",
        metroWalkTime: 12,
        tags: ["outdoor", "family-friendly", "kid-friendly", "waterfront"],
        cuisine: ["International", "Seafood"],
        priceLevel: "Mid",
        rating: 4.3,
        noise: "Lively",
        openingHours: {
          monday: "8:00-23:00",
          tuesday: "8:00-23:00",
          wednesday: "8:00-23:00",
          thursday: "8:00-23:00",
          friday: "8:00-00:00",
          saturday: "8:00-00:00",
          sunday: "8:00-23:00",
        },
        phone: "+971-4-345-6789",
        website: "https://beachhouse.ae",
        highlights: "Beachfront dining with play area for kids, perfect for families seeking casual dining by the sea.",
        parkingNote: "Paid parking at JBR",
        seatingTypes: ["outdoor", "beach", "high-chair"],
        category: "cafe",
        verified: true,
        lastUpdated: Date.now(),
      },

      // City Walk - Trendy Brunch
      {
        name: "Social House",
        nameAr: "سوشال هاوس",
        coverImage: "/images/social-house.jpg",
        gallery: ["/images/social-house-1.jpg"],
        latitude: 25.2048,
        longitude: 55.2708,
        area: "City Walk",
        nearMetro: false,
        tags: ["outdoor", "indoor"],
        cuisine: ["International", "Fusion"],
        priceLevel: "High",
        rating: 4.6,
        noise: "Lively",
        openingHours: {
          monday: "12:00-00:00",
          tuesday: "12:00-00:00",
          wednesday: "12:00-00:00",
          thursday: "12:00-01:00",
          friday: "12:00-02:00",
          saturday: "12:00-02:00",
          sunday: "12:00-00:00",
        },
        phone: "+971-4-456-7890",
        bookingUrl: "https://example.com/book/social-house",
        website: "https://socialhouse.ae",
        highlights: "Contemporary dining with both indoor and outdoor seating, known for brunches and vibrant atmosphere.",
        parkingNote: "Ample parking at City Walk",
        seatingTypes: ["outdoor", "indoor", "sofa"],
        category: "restaurant",
        verified: true,
        lastUpdated: Date.now(),
      },

      // Al Barsha - Budget Family Restaurant
      {
        name: "Ravi Restaurant",
        nameAr: "مطعم رافي",
        coverImage: "/images/ravi.jpg",
        gallery: ["/images/ravi-1.jpg"],
        latitude: 25.1124,
        longitude: 55.1975,
        area: "Al Barsha",
        nearMetro: true,
        metroStation: "Mall of the Emirates",
        metroWalkTime: 10,
        tags: ["indoor", "family-friendly"],
        cuisine: ["Pakistani", "Indian"],
        priceLevel: "Low",
        rating: 4.4,
        noise: "Lively",
        openingHours: {
          monday: "5:00-3:00",
          tuesday: "5:00-3:00",
          wednesday: "5:00-3:00",
          thursday: "5:00-3:00",
          friday: "5:00-3:00",
          saturday: "5:00-3:00",
          sunday: "5:00-3:00",
        },
        phone: "+971-4-331-5353",
        website: "https://ravi.ae",
        highlights: "Legendary affordable Pakistani cuisine, perfect for budget-conscious families seeking authentic flavors.",
        parkingNote: "Street parking available",
        seatingTypes: ["indoor", "basic"],
        category: "restaurant",
        verified: true,
        lastUpdated: Date.now(),
      },

      // Palm Jumeirah - Beach Club
      {
        name: "Riva Beach Club",
        nameAr: "نادي ريفا الشاطئي",
        coverImage: "/images/riva.jpg",
        gallery: ["/images/riva-1.jpg", "/images/riva-2.jpg"],
        latitude: 25.1124,
        longitude: 55.1397,
        area: "Palm Jumeirah",
        nearMetro: false,
        tags: ["outdoor", "waterfront"],
        cuisine: ["Mediterranean", "Seafood"],
        priceLevel: "High",
        rating: 4.8,
        noise: "Moderate",
        openingHours: {
          monday: "10:00-23:00",
          tuesday: "10:00-23:00",
          wednesday: "10:00-23:00",
          thursday: "10:00-23:00",
          friday: "10:00-00:00",
          saturday: "10:00-00:00",
          sunday: "10:00-23:00",
        },
        phone: "+971-4-567-8901",
        bookingUrl: "https://example.com/book/riva",
        website: "https://riva.ae",
        highlights: "Stunning beachfront location with Mediterranean cuisine and breathtaking sunset views.",
        parkingNote: "Valet parking available",
        seatingTypes: ["outdoor", "beach", "loungers"],
        category: "restaurant",
        verified: true,
        lastUpdated: Date.now(),
      },

      // DIFC - Upscale Cafe
      {
        name: "Jones the Grocer",
        nameAr: "جونز ذا جروسر",
        coverImage: "/images/jones.jpg",
        gallery: ["/images/jones-1.jpg"],
        latitude: 25.2138,
        longitude: 55.2811,
        area: "DIFC",
        nearMetro: true,
        metroStation: "Emirates Towers",
        metroWalkTime: 7,
        tags: ["indoor", "outdoor", "family-friendly"],
        cuisine: ["International", "Breakfast"],
        priceLevel: "High",
        rating: 4.5,
        noise: "Quiet",
        openingHours: {
          monday: "7:00-23:00",
          tuesday: "7:00-23:00",
          wednesday: "7:00-23:00",
          thursday: "7:00-23:00",
          friday: "8:00-23:00",
          saturday: "8:00-23:00",
          sunday: "8:00-23:00",
        },
        phone: "+971-4-678-9012",
        bookingUrl: "https://example.com/book/jones",
        website: "https://jonesthegrocer.com",
        highlights: "Premium all-day dining with gourmet deli, perfect for business lunches or leisurely breakfasts.",
        parkingNote: "Parking in DIFC",
        seatingTypes: ["indoor", "outdoor", "high-chair"],
        category: "cafe",
        verified: true,
        lastUpdated: Date.now(),
      },

      // Jumeirah - Kid-Friendly Cafe
      {
        name: "Tom & Serg",
        nameAr: "توم آند سيرج",
        coverImage: "/images/tom-serg.jpg",
        gallery: ["/images/tom-serg-1.jpg"],
        latitude: 25.2285,
        longitude: 55.2593,
        area: "Jumeirah",
        nearMetro: false,
        tags: ["indoor", "outdoor", "family-friendly", "kid-friendly"],
        cuisine: ["International", "Breakfast"],
        priceLevel: "Mid",
        rating: 4.6,
        noise: "Moderate",
        openingHours: {
          monday: "7:00-17:00",
          tuesday: "7:00-17:00",
          wednesday: "7:00-17:00",
          thursday: "7:00-17:00",
          friday: "7:00-17:00",
          saturday: "7:00-17:00",
          sunday: "7:00-17:00",
        },
        phone: "+971-4-789-0123",
        website: "https://tomandserg.com",
        highlights: "Industrial-chic cafe with play area, known for excellent coffee and kid-friendly atmosphere.",
        parkingNote: "Street parking",
        seatingTypes: ["indoor", "outdoor", "high-chair"],
        category: "cafe",
        verified: true,
        lastUpdated: Date.now(),
      },

      // Deira - Creek View Restaurant
      {
        name: "Al Mansour Dhow",
        nameAr: "الدو المنصور",
        coverImage: "/images/dhow.jpg",
        gallery: ["/images/dhow-1.jpg"],
        latitude: 25.2697,
        longitude: 55.3094,
        area: "Deira",
        nearMetro: true,
        metroStation: "Al Rigga",
        metroWalkTime: 15,
        tags: ["outdoor", "waterfront", "family-friendly"],
        cuisine: ["Arabic", "International"],
        priceLevel: "Mid",
        rating: 4.4,
        noise: "Quiet",
        openingHours: {
          monday: "19:30-23:00",
          tuesday: "19:30-23:00",
          wednesday: "19:30-23:00",
          thursday: "19:30-23:00",
          friday: "19:30-23:30",
          saturday: "19:30-23:30",
          sunday: "19:30-23:00",
        },
        phone: "+971-4-890-1234",
        bookingUrl: "https://example.com/book/dhow",
        website: "https://almansourdhow.ae",
        highlights: "Traditional dhow cruise dining experience on Dubai Creek with buffet dinner and creek views.",
        parkingNote: "Parking at creek",
        seatingTypes: ["outdoor", "traditional"],
        category: "restaurant",
        verified: true,
        lastUpdated: Date.now(),
      },
    ];

    for (const place of places) {
      await ctx.db.insert("places", place);
    }

    return { message: `Seeded ${places.length} places successfully` };
  },
});
